### ISSUE TITLE
Uncaught TypeError during browser creation

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#1457]
Hi,

Sorry to bother with what probably will be a very stupid question, but here goes.
I'm trying to build a Svelte app with an igv browser inside.

I've included the script tag and copy pasted the example to get started
```html
<script src="https://cdn.jsdelivr.net/npm/igv@2.10.5/dist/igv.min.js"></script>
<script>
  const igvDiv = document.getElementById('igv-div');
  igv.createBrowser(igvDiv, {}).then(function (browser) {
    console.log('browser created');
  });
</script>
<div id="igv-div" />
```
but I'm getting the following error.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'appendChild')
    at new dv (browser.js:102:19)
    at Object.createBrowser (igv-create.js:68:21)
```
  | dv | @ | browser.js:102
-- | -- | -- | --
  | createBrowser | @ | igv-create.js:68
  | Promise.then (async) |   |  
  | instance | @ | App.svelte:3
  | init | @ | index.mjs:1862
  | App | @ | App.svelte:4
  | (anonymous) | @ | main.js:3
  | (anonymous) | @ | main.js:8

Any idea where I'm going wrong?
Thanks
Matthias

**Comment by matthdsm** [comment]
Hi @turner 

Thanks for the tip, turns out my issue was that the div didn't exist yet. I'll have to check out how to make svelte create it before initializing the browser.

Thanks for the quick reply!
Matthias

**Comment by jrobinso** [comment]
To clarify what Doug was getting at, I think,  is your script tag in the head?  I think it should be in the body,  perhaps after creation of igv-div but I'm not sure order matters.   However it for sure wouldn't work in the "head".

**Comment by matthdsm** [comment]
Hi @jrobinso,

The cdn script tag is in the head, but the "custom" script tag is part of the Svelte component.

I was able to fix my issues by checking the lifecycle of the div and initializing the browser after the div is created

```html
# App.svelte
<script>
  import { onMount } from 'svelte';

  let igvBrowser;

  onMount(() => {
    console.log('mounted');
    igv.createBrowser(igvBrowser, { genome: 'hg38' }).then(function (browser) {
      console.log('browser created');
    });
  });
</script>

<main>
  <div id="igv-div" bind:this={igvBrowser} />
</main>
```
