### ISSUE TITLE
How to have the same height when loading bedGraph files

### ISSUE THREAD

**Issue by DawnEve** [igvteam/igv.js#1510]
When I load this file,
```
$ head macs2/c1_region_control_lambda.bedGraph
19      0       49470258        0.00008
```

using:
```
	{
		type: "wig",
		name: "bedGraph,C, Macs2 --extsize 1",

		url: "http://xx:8787/list/macs2/c1_region_control_lambda.bedGraph",
		height:50,
		color: "grey",
		min: "0",
		max: "30", //when comment this line, no error now. But I hope they can have the same height;
	},
```
F12 console went error:

```
igv.min.js:65

Uncaught (in promise) TypeError: t.toFixed is not a function
    at f (igv.min.js:65:52310)
    at om.Ff [as paintAxis] (igv.min.js:65:52494)
    at qd.paintAxis (igv.min.js:72:82806)
    at qd.adjustTrackHeight (igv.min.js:72:77069)
    at qd.updateViews (igv.min.js:72:76099)
```

**Comment by DawnEve** [comment]
Thank you.
