### ISSUE TITLE
Variant Track Custom change between V2 and v3

### ISSUE THREAD

**Issue by jpofmars** [igvteam/igv.js#1903]
Hello,

I have updated the IGVjs version from 2.15 to 3.08.
In version 2, I created a custom variant track from a database. This was useful because I could use the context_hook function to customize the display.
In version 3, I get several errors. I tried to find out why by adding console.log to the .js file. It seems that when we upload a real VCF file, a Variant class object is created, but not when we create a custom variant track. No Variant object was created, so the associated functions failed (alleleFreq, isFiletered ...).

Exemple of console.log with good VCF : 
igv.esm.js:67150 Variant {chr: '1', pos: 231276117, names: '2724400', referenceBases: 'C', alternateBases: 'T', …}

Exemple of console.log with Custom Track :
 // Not show here but all informations as alternateBases, filter, quality is given in the JSON.
igv.esm.js:67150 {chr: '1', position: 150332972, referenceBases: 'C', alternateBases: 'T', start: 150332971, …}

igv.esm.js:67153 TypeError: variant.alleleFreq is not a function
    at VariantTrack.draw (igv.esm.js:67151:34)
    at TrackViewport.draw (igv.esm.js:38912:34)
    at TrackViewport.repaint (igv.esm.js:38881:14)
    at TrackView.updateViews (igv.esm.js:43212:20)
    at igv.esm.js:75522:60
    at Array.map (<anonymous>)
    at _Browser.updateViews (igv.esm.js:75522:47)
    at async _Browser.resize (igv.esm.js:76368:5)
igv.esm.js:67273 Uncaught (in promise) TypeError: v.isFiltered is not a function
    at VariantTrack.getColorForFeature (igv.esm.js:67273:15)
    at VariantTrack.draw (igv.esm.js:67164:46)
    at TrackViewport.draw (igv.esm.js:38912:34)
    at TrackViewport.repaint (igv.esm.js:38881:14)
    at TrackView.updateViews (igv.esm.js:43212:20)
    at igv.esm.js:75522:60
    at Array.map (<anonymous>)
    at _Browser.updateViews (igv.esm.js:75522:47)
    at async _Browser.resize (igv.esm.js:76368:5)

I've carried out various tests such as using format 'vcf' or creating a format with registerFileFormats.
Is there a different method on version 3 for creating a track variant in custom mode that I haven't understood?
Thank you for your help. I continu to make test.

**Comment by jpofmars** [comment]
To work , i have to add this line at line 67149 of igv.esm.js

 if (!(variant instanceof Variant)) {
                    // Convert 'variant' to an instance of 'Variant'
                    // assuming 'Variant' is a constructor function available in your scope
                    try {
                        variant = new Variant([variant.chr, variant.position, variant.name, variant.ref, variant.alt, variant.quality, variant.filter, variant.infos]);
                    } catch (conversionError) {
                        console.error('Failed to convert to Variant:', conversionError);
                    }
                }

To comply, I create a “infos” field formatted like the VCF “infos” columns.

**Comment by jpofmars** [comment]
I try to generate a exemple file with the json feature and an exemple of my data (because I get my json from custom URL). But I get a different error like this : igv.esm.js:66915 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'INFO')
    at VariantTrack.postInit (igv.esm.js:66915:25)
    at async Browser.addTrack (igv.esm.js:75061:17)
    
    
Here the exemple file based on your exemple :
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link href=img/favicon.ico rel="shortcut icon">
    <title>igv.js</title>
</head>
<body>
<h2>This example illustrates embedding copy number segments directly as objects in lieu of supplying a url.</h2>
<div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>
<h4>Tracks configuration:</h4>
<script type="module">

    import igv from "./igv.esm.js"

    var igvDiv = document.getElementById("igvDiv")
    var options =
        {
            genome: "hg19",
            locus: 'chr1:629,422-16,522,294',
            tracks:
                [{
                    type: 'variant',
                    name: 'Custom Variant Track',
                    displayMode: 'EXPANDED',
                    features: [{ "chr": "1", "position": 161169065, "referenceBases": "G", "alternateBases": "A", "alleles": ["A"], "start": 161169064, "end": 161169065, "ref": "G", "alt": "A", "filter": ".", "quality": "0", "name": "G\/A", "type": "SNP", "info": { "AF": "0.50", "DP": "0", "GT": "het", "FLAG": ".", "QUAL": " 0", "Chr": "1", "Pos": 161169065, "Ref": "G", "Alt": "A", "ID": 799341, "is_filtered": 0, "in_analysis": 1 }, "infos": "AF=0.50;DP=0;FLAG=.;QUAL=0;is_filtered=0;in_analysis=1;GT=het;CID=799341;TYPE=SNP" }]
                },
                    {
                        name: "Copy number",
                        type: "seg",
                        displayMode: "EXPANDED",
                        features: [
                            {
                                "chr": "1",
                                "start": 3218610,
                                "end": 4749076,
                                "value": -0.2239,
                                "sample": "TCGA-OR-A5J2-01"
                            },
                            {
                                "chr": "1",
                                "start": 4750119,
                                "end": 11347492,
                                "value": -0.8391,
                                "sample": "TCGA-OR-A5J2-01"
                            }
                        ]
                    },
                    {
                        name: "Annotations",
                        type: "annotation",
                        displayMode: "EXPANDED",
                        features: [
                            {
                                "chr": "1",
                                "start": 3218610,
                                "end": 4749076,
                                "value": -0.2239,
                                "color": "blue",
                                "name": "Blue"
                            },
                            {
                                "chr": "1",
                                "start": 4750119,
                                "end": 11347492,
                                "value": -0.8391,
                                "color": "green",
                                "name": "Green"
                            }
                        ]
                    },
                    {
                        name: "Wig",
                        type: "wig",
                        displayMode: "EXPANDED",
                        features: [
                            {
                                "chr": "1",
                                "start": 3218610,
                                "end": 4749076,
                                "value": -0.2239
                            },
                            {
                                "chr": "1",
                                "start": 4750119,
                                "end": 11347492,
                                "value": -0.8391
                            }
                        ]
                    },
                ]
        }
    igv.createBrowser(igvDiv, options)
        .then(function (browser) {
            console.log("Created IGV browser")
        })
</script>
</body>
</html>
```


So I will try to explain how I create my track. Note I use vuejs3 to implement the browser.

```
 igvDiv.value = document.getElementById("igv-div");

// Init options
let options = ref(
    {
        genome: "hg38",
        loadDefaultGenomes: false,
        genomeList: '/igv/filedata/genomes.json',
        tracks: [

        ],
        // reference: ,
        showLoadFileWidget: true
    });


// Track generation:
 url = `/analysis/igvdata/?chromosome=$CHR&start=$START&end=$END&version=` + props.version_id + `&analysis_id=` + props.analysis_id + `&genome=` + usedGenome.value + `&mode=` + props.mode + `&vartype=` + track.type + `&formid=` + formID

  let igvtrack = {
        name: 'trackname',
        sourceType: 'custom',
        squishedRowHeight: 1,
        expandedCallHeight: 6,
        labelAllFeatures: false,
        type: "variant",
        displayMode: "EXPANDED",
        height: 100,
        visibilityWindow: 10000,
format:'vcf',
source = {
            url: url,
            method: 'GET',
            contentType: 'application/json',
            queryable: true,
        }
}
options.value.tracks.push(igvtrack);

 igv.createBrowser(igvDiv.value, options.value)
        .then(function (browser) {
            browser.on('trackclick', function (track, popoverData) {
                var markup = '<table class="styled-table">';
                if (!popoverData || !popoverData.length) {
                    return false;
                }  
               // I call different popover depending on my custom tracks.
            });
            igvBrowser = browser;
            
        })

```


To be able to display variant like when I upload a VCF, I need to perform different change in the igv.esm.js file:
Line 67087 : 
```
 for (let v of features) {
                console.log('v', v)
                if (!(v instanceof Variant)) {
                    // Convert 'variant' to an instance of 'Variant'
                    // assuming 'Variant' is a constructor function available in your scope
                    try {
                        let v2 = new Variant([v.chr, v.position, v.name, v.ref, v.alt, v.quality, v.filter, v.infos]);
                        v2.row = v.row
                        v = v2
                    } catch (conversionError) {
                        console.error('Failed to convert to Variant:', conversionError);
                    }
                }
                ...
```
                
Line 67338: 
```
 for (let v of featureList) {

            console.log('v', v)
            if (!(v instanceof Variant)) {
                // Convert 'variant' to an instance of 'Variant'
                // assuming 'Variant' is a constructor function available in your scope
                try {
                    v = new Variant([v.chr, v.position, v.name, v.ref, v.alt, v.quality, v.filter, v.infos]);

                } catch (conversionError) {
                    console.error('Failed to convert to Variant:', conversionError);
                }
            }
```

Line 33490: (If I have an int value in my JSON instead of a string I get an error:
```
 if (typeof key === 'string') {
                        key = key.replaceAll(' ', '+').toUpperCase();
                    } else {
                        key = String(key).replaceAll(' ', '+').toUpperCase();
                    }
```
I have a last issue with the click event, on my custom track the click works only on the first position of the variant, so if I have a deletion the click does not work after the first position. With real VCF that works.

Sorry to not be able to create a good exemple.

Thank you !

**Comment by jpofmars** [comment]
I checked how the VCF was analyzed and tested several combinations. I test the “chr , pos , names, referenceBases, alternateBases, quality, filter, info” keys. I test the mapping. I test information formatted as a VCF. I'm testing the info as a JSON.

I'd like to generate an example with a JSON instead of the webservice, but I get a different error like the one I described earlier.
I've tried to simplify this example:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link href=img/favicon.ico rel="shortcut icon">
    <title>igv.js</title>
</head>

<body>
<div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>
<script type="module">
    import igv from "./igv.esm.js"
    var igvDiv = document.getElementById("igvDiv")
    var options =
        {
            genome: "hg19",
            locus: 'chr1:150332900-150332999',
            tracks:
                [{
                    type: 'variant',
                    name: 'Custom Variant Track',
                    displayMode: 'EXPANDED',
                    features: [
                            {

                                chr: "1",
                                pos: 150332972,
                                referenceBases: "C",
                                alternateBases: "T",
                                names: "C/T",
                                filter: ".",
                                quality: "0",
                                info: "AF=0.50;DP=0;FLAG=.;QUAL=0;GT=het;TYPE=SNP;"
                            }
                    ]
                }]
        }
    igv.createBrowser(igvDiv, options)
        .then(function (browser) {
            console.log("Created IGV browser")
        })
</script>
</body>
</html>
```

**Comment by jrobinso** [comment]
The info field needs to be an object, not a string, like

```
info: {
   AF: 0.50,
   DP: 0,
   FLAG: '.',
   QUAL: 0,
   GT: 'het',
   TYPE: 'SNP'
}
}
```
