### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith') in v3+

### ISSUE THREAD

**Issue by lpryszcz** [igvteam/igv.js#1913]
hi @jrobinso , I'm having issues when running v3+.  console output:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Bk.update (chromAliasDefaults.js:54:26)
    at new Bk (chromAliasDefaults.js:14:14)
    at Ck.init (genome.js:66:31)
    at async Ck.createGenome (genome.js:28:9)
    at async _k.loadReference (browser.js:750:53)
    at async _k.loadSessionObject (browser.js:620:9)
    at async Object.createBrowser (igv-create.js:78:18)
browser.js:2461 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at _k.Ek (browser.js:2461:33)
```

v2.15.13 works ok so it's not urgent. 

greetings from Barcelona!

**Comment by lpryszcz** [comment]
This is still a problem with v3.1.3 

```
Uncaught (in promise) TypeError: n is undefined
    update chromAliasDefaults.js:56
    EA chromAliasDefaults.js:14
    init genome.js:67
```

**Comment by jrobinso** [comment]
@could you give me some steps to reproduce?   Which genome are you selecting?

**Comment by jrobinso** [comment]
I can't really do anything about this without some steps to reproduce.   Could post your reference genome configuration, or tell me what IGV predefined genome you are using.
