### ISSUE TITLE
TypeError when running removeBrowser

### ISSUE THREAD

**Issue by bartcharbon** [igvteam/igv.js#1918]
When I call "removeBrowser" I run into the exception below.

I'm using ijg.js v3.1.0

Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at igv.esm.js:74664:97
    at f (igv.esm.js:77436:26)
    at Array.filter (<anonymous>)
    at _Browser.findTracks (igv.esm.js:77439:32)
    at MutationObserver.updateROIDimensions (igv.esm.js:74664:36)

**Comment by jrobinso** [comment]
Yes, I can reproduce this.  You should be able to ignore the error with no consequences.

**Comment by jrobinso** [comment]
This is now fixed
