### ISSUE TITLE
Building igv.js under cygwin

### ISSUE THREAD

**Issue by dtsamitros** [igvteam/igv.js#812]
I was able to build igv.js under Linux but building igv.js under Cygwin produces the following error:
```
$ npm run grunt

> igv@2.1.0 grunt C:\Temp\igv.js
> node node_modules/grunt/bin/grunt

>> Local Npm module "babel-core" not found. Is it installed?
(node:11104) ExperimentalWarning: The http2 module is an experimental API.

Running "babel:dist" (babel) task

Running "concat:css" (concat) task

Running "embed-css" task

Running "concat:igv" (concat) task

Running "uglify:igv" (uglify) task
{ SyntaxError: Unterminated string constant
  at JS_Parse_Error.get (<anonymous>:75:23)
  at formatError (util.js:609:16)
  at formatValue (util.js:513:18)
  at inspect (util.js:293:10)
  at format (util.js:160:12)
  at Console.log (console.js:130:21)
  at C:\Temp\igv.js\node_modules\grunt-contrib-uglify-es\tasks\uglify.js:144:17
  at Array.forEach (<anonymous>:null:null)
  at Object.<anonymous> (C:\Temp\igv.js\node_modules\grunt-contrib-uglify-es\tasks\uglify.js:78:16)
  at Object.<anonymous> (C:\Temp\igv.js\node_modules\grunt\lib\grunt\task.js:252:15)
  at Object.thisTask.fn (C:\Temp\igv.js\node_modules\grunt\lib\grunt\task.js:70:16)
  at Object.<anonymous> (C:\Temp\igv.js\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (C:\Temp\igv.js\node_modules\grunt\lib\util\task.js:244:24)
  at Task.<anonymous> (C:\Temp\igv.js\node_modules\grunt\lib\util\task.js:293:12)
  at C:\Temp\igv.js\node_modules\grunt\lib\util\task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

  message: 'Unterminated string constant',
  filename: 'igv.js',
  line: 32,
  col: 15,
  pos: 967 }
>> Uglifying source dist/igv.js failed.
Warning: Uglification failed.
Unterminated string constant.
Line 32 in dist/igv.js
 Use --force to continue.
```
Are there perhaps some additional steps I should be following in order to build successfully?

**Comment by dtsamitros** [comment]
The following line addition in `Gruntfile.js` seems to fix the problem

```js
        ping = grunt.file.read('tmp/igv-all.css');
+       ping = ping.replace(/\r\n/g, '\\n');
        pong = ping.replace(/\n/g, '\\n');
```
and can now build successfully under windows as well.. (and all the tests pass just fine)
